apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    user: admin
    secureJsonData:
      password: password
    database: zeta_telemetry
    jsonData:
      sslmode: disable
      postgresVersion: 15
